---
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: CHANDU
      MYSQL_ROOT_USER: CHANDU
      MYSQL_PASSWORD: CHANDU
      MYSQL_DATABASE: CHANDU
  myhttpd:
    image: httpd
    ports:
      - 9090:80
    links:
      - database:mysql
  myphp:
    image: php:7.2-apache
    links:
      - database:mysql
      - myhttpd:httpd


EXPLANATION: 
      Apache : Web server, handles requests
      MySQL: Database server
      PHP: 
          🛑 Why PHP Doesn’t Need a Port ?
              - PHP is not a web server.
              - It’s a scripting language runtime, used behind Apache or Nginx.
              - It executes code and returns output 
