---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: temporary-data-storage
spec:
  containers:
    - name: my-nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8080
      volumeMounts:
        - name: nginx-volumes
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-volumes
      persistentVolumeClaim:
        claimName: pvc
