---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    test: volumes
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home
