---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    test: pvc-volumes
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

