---
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: chandu
    volumes:
      - mydb: /var/lib/mysql
  mywordpress:
    image: wordpress
    ports:
      - 9090:80
    volumes:
      - web: /var/www/html
volumes:
  mydb:
  mywordpress:
