---
services:
  hub:
    image: selenium/hub
    ports:
      - 4400:4444
    container_name: testing
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901:5900
    links:
      - hub:selenium/hub
    container_name: chrome
  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5902:5900
    links:
      - hub:selenium/hub
    container_name: firfox

check:
  REAL VNC viewer and provide ip of chrome and firefox in search bar with port number
