---
services:
  hub:
    image: selenium/hub
    ports:
      - 4400:4444
<<<<<<< HEAD
      container_name: testing
=======
    container_name: testing
>>>>>>> 28e7892 (.)
  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901:5900
    links:
      - hub:selenium/hub
<<<<<<< HEAD
      container_name: chrome
=======
    container_name: chrome
>>>>>>> 28e7892 (.)
  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5902:5900
    links:
      - hub:selenium/hub
<<<<<<< HEAD
      container_name: firefox
=======
    container_name: firfox
>>>>>>> 28e7892 (.)




how it work:
 
     install realvnc viewer
        search bar : 54.219.128.128:5901 / 54.219.128.128:5902
        p/w : secret
           * tap any where app-networks-webbrowsing-chrome/firefox
         
