---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
  labels:
    app: proxy
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: proxy
    spec:
      containers:
        - name: my-nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080

