---
apiVersion: v1
kind: Secret
metadata:
  name: secret-mysql
  labels:
    author: chandu
type: Opaque
stringData:
  a: chandu

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: datastorage
spec:
  containers:
    - name: database
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-mysql
              key: a

