---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-jenkins
  labels:
    work: ci-cd
spec:
  replicas: 2
  serviceName: service-jenkin
  selector:
    matchLabels:
      work: ci-cd
  template:
    metadata:
      name: jenkins-pod
      labels:
        work: ci-cd
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: service-jenkins
  labels:
    work: ci-cd
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 9090
  selector:
    work: ci-cd

For statefulset only we use {serviceName} in above 

