---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    storge: temporary
spec:
  replicas: 2
  selector:
    matchLabels:
      storage: temporary
  template:
    metadata:
      name: tomcat-pod
      labels:
        storage: temporary
    spec:
      containers:
        - name: tomee
          image: tomcat
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    storage: temporary
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 9090
      nodePort: 30114
  selector:
    storage: temporary
  
