FROM jenkins/jenkins
MAINTAINER chandu
USER root
WORKDIR /
RUN apt-get update
RUN apt-get install -y git maven
EXPOSE 90
ADD https://get.jenkins.io/war-stable/2.504.3/jenkins.war .
COPY tomcat-user.xml .
VOLUME /chandu
